# Generated by Django 4.2.2 on 2023-06-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgroundzero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fch_creacion',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_artista',
            field=models.ForeignKey(db_column='idArtista', on_delete=django.db.models.deletion.CASCADE, to='appgroundzero.artista', verbose_name='Id del artista'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='appgroundzero.categoria', verbose_name='Id de la categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nmb_producto',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
    ]
